import { TaxiData } from "./LocalTaxiHead";

export type PageDataType = Record<string, TaxiData>;
export const PAGE_DATA:PageDataType = {
    'kochi-airport-to-calicut-taxi': {
        'title': "Kochi Airport to Calicut Taxi",
        'subtext': 'Kochi to Calicut cabs',
        'sedan': 4700,
        'lodgy': 5500,
        'innova': 6200,
        'distance': '120 Km',
        'time': '3.5 Hours',
    },
    'kochi-airport-to-kannur-taxi':{
        'title': "Kochi Airport to Kannur Taxi",
        'subtext': 'Kochi to Kannur cabs',
        'sedan': 7000,
        'lodgy': 8100,
        'innova': 9200,
        'distance': '260 Km',
        'time': '6 Hours',
    },
    'kochi-airport-to-alleppy-taxi': {
        'title': "Kochi Airport to Alleppey Taxi",
        'subtext': 'Kochi to Alleppey cabs',
        'sedan': 2300,
        'lodgy': 2700,
        'innova': 3000,
        'distance': '90 Km',
        'time': '2.5 Hours',

    },
    'kochi-airport-to-idukki-taxi': {
        'title': "Kochi Airport to Idukki Taxi",
        'subtext': 'Kochi to Idukki cabs',
        'sedan': 2800,
        'lodgy': 3300,
        'innova': 3800,
        'distance': '115 Km',
        'time': '3.5 Hours',
    },
        'kochi-airport-to-kasargod-taxi': {
        'title': "Kochi Airport to Kasargod Taxi",
        'subtext': 'Kochi to Kasargod cabs',
        'sedan': 9400,
        'lodgy': 10800,
        'innova': 12300,
        'distance': '350 Km',
        'time': '8.5 Hours',
    },
    'kochi-airport-to-kollam-taxi': {
        'title': "Kochi Airport to Kollam Taxi",
        'subtext': 'Kochi to Kollam cabs',
        'sedan': 4500,
        'lodgy': 5300,
        'innova': 6000,
        'distance': '170 Km',
        'time': '4 Hours',
    },
    'kochi-airport-to-kottayam-taxi': {
        'title': "Kochi Airport to Kottayam Taxi",
        'subtext': 'Kochi to Kottayam cabs',
        'sedan': 2300,
        'lodgy': 2700,
        'innova': 3000,
        'distance': '90 Km',
        'time': '2 Hours',
    },
    'kochi-airport-to-malappuram-taxi': {
        'title': "Kochi Airport to Malappuram Taxi",
        'subtext': 'Kochi to Malappuram cabs',
        'sedan': 3700,
        'lodgy': 4200,
        'innova': 4700,
        'distance': '130 Km',
        'time': '4 Hours',
    },
    'kochi-airport-to-munnar-taxi': {
        'title': "Kochi Airport to Munnar Taxi",
        'subtext': 'Kochi to Munnar cabs',
        'sedan': 3000,
        'lodgy': 3500,
        'innova': 4000,
        'distance': '110 Km',
        'time': '3.5 Hours',
    },
    'kochi-airport-to-palakkad-taxi': {
        'title': "Kochi Airport to Palakkad Taxi",
        'subtext': 'Kochi to Palakkad cabs',
        'sedan': 3100,
        'lodgy': 3600,
        'innova': 4000,
        'distance': '115 Km',
        'time': '3 Hours',
    },
    'kochi-airport-to-pathanamthitta-taxi': {
        'title': "Kochi Airport to Pathanamthitta Taxi",
        'subtext': 'Kochi to Pathanamthitta cabs',
        'sedan': 3700,
        'lodgy': 4200,
        'innova': 4800,
        'distance': '140 Km',
        'time': '3.5 Hours',
    },
    'kochi-airport-to-ranni-taxi': {
        'title': "Kochi Airport to Ranni Taxi",
        'subtext': 'Kochi to Ranni cabs',
        'sedan': 3300,
        'lodgy': 3800,
        'innova': 4300,
        'distance': '120 Km',
        'time': '3 Hours',
    },
    'kochi-airport-to-trivandrum-taxi': {
        'title': "Kochi Airport to Trivandrum Taxi",
        'subtext': 'Kochi to Trivandrum cabs',
        'sedan': 6100,
        'lodgy': 7000,
        'innova': 8000,
        'distance': '230 Km',
        'time': '5 Hours',
    },
    'kochi-airport-to-waynad-taxi': {
        'title': "Kochi Airport to Wayanad Taxi",
        'subtext': 'Kochi to Wayanad cabs',
        'sedan': 6600,
        'lodgy': 7600,
        'innova': 8600,
        'distance': '245 Km',
        'time': '6.5 Hours',
    },
}